server.port: 8080
server.error.include-message: always

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**
            - Path=/api/v1/available_dates/**
            - Path=/api/v1/reviews/**
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/authentication/**
            - Path=/api/v1/roles/**
            - Path=/api/v1/users/**
        - id: management-service
          uri: lb://management-service
          predicates:
            - Path=/api/v1/animals/**
            - Path=/api/v1/enclosures/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/advisors/**
            - Path=/api/v1/farmers/**
            - Path=/api/v1/notifications/**
            - Path=/api/v1/profiles/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
      instance:
      leaseRenewalIntervalInSeconds: 5
      leaseExpirationDurationInSeconds: 5
  instance:
    hostname: localhost
